// <auto-generated />
using System;
using Bulky.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241223190954_addForienKeyForProduct")]
    partial class addForienKeyForProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            CategoryId = 2,
                            Description = "An introduction to C# programming language.",
                            ISBN = "9781234567890",
                            Price = 29.989999999999998,
                            Price100 = 22.989999999999998,
                            Price50 = 25.989999999999998,
                            Title = "C# Programming Basics"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane Smith",
                            CategoryId = 3,
                            Description = "A deep dive into the .NET framework.",
                            ISBN = "9781234567891",
                            Price = 39.990000000000002,
                            Price100 = 30.989999999999998,
                            Price50 = 35.990000000000002,
                            Title = "Advanced .NET"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Emily Davis",
                            CategoryId = 2,
                            Description = "Mastering EF Core for database management.",
                            ISBN = "9781234567892",
                            Price = 34.990000000000002,
                            Price100 = 27.989999999999998,
                            Price50 = 30.989999999999998,
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Michael Brown",
                            CategoryId = 3,
                            Description = "Comprehensive guide to building web apps with ASP.NET MVC.",
                            ISBN = "9781234567893",
                            Price = 44.990000000000002,
                            Price100 = 37.990000000000002,
                            Price50 = 40.990000000000002,
                            Title = "ASP.NET MVC Guide"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Sarah Wilson",
                            CategoryId = 3,
                            Description = "Learn Blazor to build modern web applications.",
                            ISBN = "9781234567894",
                            Price = 24.989999999999998,
                            Price100 = 18.989999999999998,
                            Price50 = 20.989999999999998,
                            Title = "Blazor for Beginners"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
